root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  help/about: about/README.md
  help/product: product/README.md
  help/collectives: collectives/README.md
  help/backers-and-sponsors: financial-contributors/README.md
  help/backers-and-sponsors/sponsor-faq: financial-contributors/organizations/README.md
  help/backers-and-sponsors/payment: financial-contributors/payments.md
  help/backers-and-sponsors/collective-to-collective-donations: financial-contributors/collectives/collective-to-collective-donations.md
  help/backers-and-sponsors/gift-cards: financial-contributors/organizations/gift-cards.md
  help/backers-and-sponsors/bulk-transfers: financial-contributors/organizations/bulk-transfers.md
  help/backers-and-sponsors/website-badge: financial-contributors/website-badge.md
  help/backers-and-sponsors/sustainer-resources: financial-contributors/organizations/sustainer-resources.md
  help/expenses: expenses/README.md
  help/hosts: fiscal-hosts/README.md
  help/hosts/become-host: fiscal-hosts/become-a-fiscal-host.md
  help/hosts/create-a-fiscal-host: fiscal-hosts/create-a-fiscal-host.md
  help/hosts/fiscal-host-settings: fiscal-hosts/fiscal-host-settings.md
  help/hosts/invoices: fiscal-hosts/invoices.md
  help/hosts/payouts: fiscal-hosts/payouts.md
  help/hosts/host-dashboard: fiscal-hosts/fiscal-host-dashboard.md
  help/hosts/add-funds-manually: fiscal-hosts/add-funds-manually.md
  help/hosts/refunds: fiscal-hosts/refunds.md
  help/hosts/host-fees: fiscal-hosts/fiscal-hosts-fees.md
  help/hosts/local-tax: fiscal-hosts/local-tax.md
  help/hosts/sponsor-agreement: fiscal-hosts/sponsor-agreement.md
  help/hosts/open-source-collective: fiscal-hosts/open-source-collective.md
  help/developers: contributing/development/README.md
  help/developers/dev-contribution-guide: contributing/development/dev-contribution-guide.md
  help/developers/guidelines: contributing/development/best-practice-guidelines.md
  help/developers/bounties: contributing/development/bounties.md
  help/developers/api: contributing/development/api/README.md
  help/developers/api/members: contributing/development/api/members.md
  help/developers/api/users-emails: contributing/development/api/users-emails.md
  help/developers/api/collectives: contributing/development/api/collectives.md
  help/developers/api/events: contributing/development/api/events.md
  help/developers/readme-integration: contributing/development/readme-integration.md
  help/developers/architecture: contributing/development/architecture.md
  help/developers/postgres-database: contributing/development/postgres-database.md
  help/developers/paypal: contributing/development/paypal.md
  help/developers/post-donation-redirect: contributing/development/post-donation-redirect.md
  help/developers/custom-tweets: contributing/development/custom-tweets.md
  help/developers/manual-reporting: contributing/development/manual-reporting.md
  help/developers/github-permissions: contributing/development/github-permissions.md
  help/developers/translations: contributing/development/translations.md
  help/developers/testing-with-cypress: contributing/development/testing-with-cypress.md
  help/developers/collectives-locations: contributing/development/collectives-locations.md
  help/projects: internal/projects/README.md
  help/projects/maintainerati-berlin-2019: internal/projects/maintainerati-berlin-2019.md
  help/projects/season-of-docs-2019: internal/projects/season-of-docs-2019.md
  help/design: contributing/design/README.md
  help/design/understanding-the-design-workflow: contributing/design/understanding-the-design-workflow.md
  help/design/untitled: contributing/design/contribution-guidelines.md
  help/the-open-collective-way: internal/the-open-collective-way/README.md
  help/the-open-collective-way/core-contributors-guidelines: internal/the-open-collective-way/core-contributors-guidelines.md
  help/the-open-collective-way/core-contributors-communication: internal/the-open-collective-way/core-contributors-communication.md
  help/the-open-collective-way/core-contributors-expenses: internal/the-open-collective-way/core-contributors-expenses.md
  help/the-open-collective-way/core-contributors-leave: internal/the-open-collective-way/core-contributors-leave.md
  help/the-open-collective-way/core-contributors-compensation: internal/the-open-collective-way/core-contributors-compensation.md